version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    restart: always

  web:
    build:
      context: .
      dockerfile: Web/DesignAndBuilding.Web/Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Server=db;Database=DesignAndBuilding;User=sa;Password=YourStrong!Passw0rd;MultipleActiveResultSets=true"